In [1]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  7359.921 
Prediction:
 [ 78.609215  90.85704   91.20816  100.16674   67.95611 ]
10 Cost:  8.009567 
Prediction:
 [154.44905 182.03023 181.03264 197.98405 137.50249]
20 Cost:  7.9034624 
Prediction:
 [154.66837 182.3131  181.30136 198.27742 137.72244]
30 Cost:  7.8648324 
Prediction:
 [154.65887 182.3209  181.29909 198.27568 137.7326 ]
40 Cost:  7.8264375 
Prediction:
 [154.64876 182.32793 181.29605 198.27309 137.74211]
50 Cost:  7.7882032 
Prediction:
 [154.63863 182.33488 181.29298 198.2705  137.7516 ]
60 Cost:  7.750212 
Prediction:
 [154.62856 182.34184 181.28996 198.2679  137.76106]
70 Cost:  7.712416 
Prediction:
 [154.6185  182.34877 181.28693 198.2653  137.7705 ]
80 Cost:  7.6747956 
Prediction:
 [154.60847 182.3557  181.28392 198.26274 137.77992]
90 Cost:  7.6374083 
Prediction:
 [154.59846 182.36258 181.2809  198.26015 137.78929]
100 Cost:  7.6002197 
Prediction:
 [154.58852 182.36946 181.2779  198.25758 137.79866]
110 Cost:  7.563211 
Prediction:
 [154.57855 182.3763

950 Cost:  5.0687284 
Prediction:
 [153.83391 182.89014 181.05096 198.06018 138.51001]
960 Cost:  5.045269 
Prediction:
 [153.82603 182.89557 181.04858 198.05807 138.51746]
970 Cost:  5.021943 
Prediction:
 [153.8182  182.901   181.04623 198.056   138.5249 ]
980 Cost:  4.998727 
Prediction:
 [153.81036 182.90639 181.04387 198.05388 138.5323 ]
990 Cost:  4.975709 
Prediction:
 [153.80257 182.91177 181.04155 198.05183 138.53969]
1000 Cost:  4.9527254 
Prediction:
 [153.79478 182.91714 181.0392  198.04974 138.54707]
1010 Cost:  4.9299216 
Prediction:
 [153.78705 182.92252 181.0369  198.04768 138.55443]
1020 Cost:  4.9071836 
Prediction:
 [153.7793  182.92784 181.03455 198.0456  138.56177]
1030 Cost:  4.884633 
Prediction:
 [153.77158 182.93317 181.03226 198.04355 138.56908]
1040 Cost:  4.8621635 
Prediction:
 [153.76389 182.93848 181.02994 198.0415  138.57639]
1050 Cost:  4.839801 
Prediction:
 [153.75621 182.94379 181.02763 198.03944 138.58366]
1060 Cost:  4.817606 
Prediction:
 [153.748

1980 Cost:  3.2063134 
Prediction:
 [153.12811 183.37796 180.83974 197.86804 139.18341]
1990 Cost:  3.1928039 
Prediction:
 [153.1222  183.38206 180.83797 197.86641 139.18907]
2000 Cost:  3.1793458 
Prediction:
 [153.1163  183.38614 180.83623 197.86476 139.19475]


In [5]:
import tensorflow as tf
# for reproducibility
tf.set_random_seed(777)

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_data, Y: y_data}
    )
    
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  76.698105 
Prediction:
 [[162.98685]
 [190.79396]
 [190.71529]
 [206.02625]
 [145.72382]]
100 Cost:  6.8102064 
Prediction:
 [[155.48677]
 [181.97147]
 [181.92232]
 [196.4637 ]
 [139.03165]]
200 Cost:  6.4628325 
Prediction:
 [[155.38765]
 [182.03926]
 [181.89177]
 [196.4429 ]
 [139.11954]]
300 Cost:  6.133822 
Prediction:
 [[155.2912 ]
 [182.10527]
 [181.86205]
 [196.42271]
 [139.20505]]
400 Cost:  5.82213 
Prediction:
 [[155.1973 ]
 [182.16953]
 [181.83311]
 [196.40309]
 [139.28825]]
500 Cost:  5.526853 
Prediction:
 [[155.10588]
 [182.23206]
 [181.80493]
 [196.384  ]
 [139.36922]]
600 Cost:  5.2471585 
Prediction:
 [[155.0169 ]
 [182.29291]
 [181.77748]
 [196.36546]
 [139.448  ]]
700 Cost:  4.982191 
Prediction:
 [[154.9303 ]
 [182.35217]
 [181.7508 ]
 [196.34746]
 [139.52466]]
800 Cost:  4.731164 
Prediction:
 [[154.84598]
 [182.40984]
 [181.72478]
 [196.32994]
 [139.59926]]
900 Cost:  4.493383 
Prediction:
 [[154.76392]
 [182.46599]
 [181.69946]
 [196.31291]
 [139.67183]]