In [4]:
nums = range(5)
print(nums)

range(0, 5)


In [5]:
print(nums[2:4])

range(2, 4)


In [6]:
print(nums[2:])

range(2, 5)


In [7]:
print(nums[:2])

range(0, 2)


In [8]:
print(nums[:])

range(0, 5)


In [9]:
print(nums[:-1])

range(0, 4)


In [12]:
import numpy as np
b = np.array([
    [1, 2, 3, 4],  # 1 row
    [5, 6, 7, 8],  # 2 row
    [9, 10, 11, 12]# 3 row
])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(b[:, 1])

[ 2  6 10]


In [14]:
print(b[-1])

[ 9 10 11 12]


In [15]:
print(b[-1, :])

[ 9 10 11 12]


In [16]:
print(b[-1, ...])

[ 9 10 11 12]


In [18]:
print(b[0:2, :])

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

# 전체 Row 중에서 마지막 Column을 제외한 전체
x_data = xy[:, 0:-1]
# 전체 Row 중에서 마지막 Column만
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [29]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], 
        feed_dict={X: x_data, Y: y_data}
    )
    if step % 200 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 9478.495 
Prediction:
 [[62.825512]
 [73.05417 ]
 [73.14898 ]
 [81.46414 ]
 [53.510914]
 [41.72551 ]
 [64.17871 ]
 [52.174763]
 [69.79098 ]
 [68.255196]
 [59.248974]
 [57.957165]
 [73.74173 ]
 [58.525448]
 [64.28799 ]
 [76.05092 ]
 [52.785908]
 [78.82617 ]
 [70.39322 ]
 [63.52754 ]
 [74.35598 ]
 [70.38225 ]
 [70.58485 ]
 [59.079807]
 [75.30197 ]]
200 Cost: 8.491321 
Prediction:
 [[154.25058]
 [183.10686]
 [181.50061]
 [199.44806]
 [137.50162]
 [103.63819]
 [152.4178 ]
 [117.47869]
 [172.65845]
 [163.50784]
 [144.3327 ]
 [141.91829]
 [185.7069 ]
 [151.64035]
 [152.95566]
 [187.69455]
 [141.54129]
 [184.6706 ]
 [177.11316]
 [158.99469]
 [177.8614 ]
 [173.59674]
 [169.26036]
 [151.31003]
 [189.34169]]
400 Cost: 8.255752 
Prediction:
 [[154.18178 ]
 [183.18353 ]
 [181.49559 ]
 [199.42422 ]
 [137.61478 ]
 [103.711716]
 [152.32777 ]
 [117.30636 ]
 [172.74454 ]
 [163.56111 ]
 [144.31235 ]
 [141.96143 ]
 [185.72354 ]
 [151.69138 ]
 [152.88696 ]
 [187.74005 ]
 [141.66171 ]
 [184.51404 ]

In [32]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 110]]}))

Your score will be  [[193.5753]]


In [33]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[188.6076 ]
 [175.22841]]


In [38]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue'
)

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32 ,shape=[None, 3])
Y = tf.placeholder(tf.float32 ,shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess,coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    # 학습 시킬때 배치 사용
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_batch, Y: y_batch}
    )
    
    if step % 200 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
coord.request_stop()
coord.join(threads)

0 Cost:  98956.17 
Prediction:
 [[-138.22705 ]
 [-181.8019  ]
 [-170.7611  ]
 [-189.89299 ]
 [-139.25996 ]
 [-110.44836 ]
 [-143.49687 ]
 [-107.835434]
 [-178.27782 ]
 [-175.12645 ]]
200 Cost:  101.0052 
Prediction:
 [[162.05356 ]
 [180.61195 ]
 [185.51836 ]
 [198.5808  ]
 [137.13527 ]
 [ 94.209755]
 [147.54903 ]
 [108.24688 ]
 [161.3328  ]
 [140.58345 ]]
400 Cost:  84.09767 
Prediction:
 [[161.29024]
 [181.01248]
 [185.20035]
 [198.64221]
 [137.4319 ]
 [ 95.21164]
 [147.83154]
 [108.74805]
 [162.51108]
 [142.69402]]
600 Cost:  70.08826 
Prediction:
 [[160.59421 ]
 [181.37726 ]
 [184.91013 ]
 [198.6985  ]
 [137.70146 ]
 [ 96.12529 ]
 [148.09032 ]
 [109.207214]
 [163.5856  ]
 [144.61975 ]]
800 Cost:  58.485626 
Prediction:
 [[159.95955]
 [181.7094 ]
 [184.64523]
 [198.75003]
 [137.94633]
 [ 96.95842]
 [148.32733]
 [109.62795]
 [164.56544]
 [146.37686]]
1000 Cost:  48.88135 
Prediction:
 [[159.38092 ]
 [182.0118  ]
 [184.40352 ]
 [198.79732 ]
 [138.16876 ]
 [ 97.718124]
 [148.54451 ]
 [1

In [39]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

Your score will be  [[169.72974]]


In [40]:
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Other scores will be  [[155.55643]
 [190.30804]]
