### Scores => Probabilities

`hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)`

어떤 Label에 해당하는지 확률(Probabilities)로 나타나게 됨.

### cost function: cross entropy

`cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))`

### Test & One-hot encoding

`hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)`

In [9]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1], # 2
          [0, 0, 1], # 2
          [0, 0, 1], # 2
          [0, 1, 0], # 1
          [0, 1, 0], # 1
          [0, 1, 0], # 1
          [1, 0, 0], # 0
          [1, 0, 0]] # 0

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})
        
        if step % 400 == 0:
            print(step, cost_val)
    
    print('================================')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))
    
    print('================================')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))
    
    print('================================')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))
    
    print('================================')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 18.406042
400 0.43663403
800 0.2853667
1200 0.21394038
1600 0.17951033
2000 0.15438387
[[3.1273873e-03 9.9686474e-01 7.8466992e-06]] [1]
[[0.8940115  0.09865826 0.00733032]] [0]
[[1.1744099e-08 3.2090070e-04 9.9967909e-01]] [2]
[[3.1273975e-03 9.9686474e-01 7.8467137e-06]
 [8.9401150e-01 9.8658204e-02 7.3303264e-03]
 [1.1744099e-08 3.2090070e-04 9.9967909e-01]] [1 0 2]
