### Training and Test datasets
학습 데이터와 테스트 데이터를 분리하기

### Learning rate
- Large learning rate: Overshooting
- Small learning rate: Many iterations until convergence and traping in local mimima

### Non-normalized inputs
- min-max sclae 적용해서 0~1 사이의 값으로 normalize함.

In [5]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    
    # Calculate the accuracy
    print("Accuracy:", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 2.5813289 [[-0.22656097 -0.6242891   0.68022853]
 [-1.1389139   0.00211243 -0.44347882]
 [ 0.88777834  0.3630321   0.45943907]]
1 1.7263864 [[-0.20534629 -0.62920827  0.663933  ]
 [-0.98651654 -0.04457146 -0.54919225]
 [ 1.0341109   0.34379548  0.33234322]]
2 1.1250732 [[-0.19634849 -0.64269495  0.66842186]
 [-0.8782985  -0.13831529 -0.5636664 ]
 [ 1.1216134   0.28227127  0.306365  ]]
3 0.9754757 [[-0.20928532 -0.63503915  0.6737029 ]
 [-0.8826602  -0.11671906 -0.5809009 ]
 [ 1.0909852   0.33357427  0.28569022]]
4 0.95349634 [[-0.21564783 -0.63773614  0.6827624 ]
 [-0.8503764  -0.15140247 -0.5785013 ]
 [ 1.0972329   0.33089757  0.28211913]]
5 0.93928546 [[-0.22719598 -0.6345398   0.6911142 ]
 [-0.8471383  -0.15333407 -0.5798078 ]
 [ 1.07479     0.35920525  0.27625442]]
6 0.92684656 [[-0.2350167  -0.6353339   0.699729  ]
 [-0.8244299  -0.17696564 -0.5788846 ]
 [ 1.0726459   0.36594212  0.2716617 ]]
7 0.9153318 [[-0.24531375 -0.63335055  0.70804274]
 [-0.816014   -0.18494768 -0.5793184